[package]
name = "boof"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bincode = "1.3.3"
nix = { version = "0.26.2", default-features = false, features = ["signal"] }
serde = { version = "1.0.183", features = ["derive"] }

[dev-dependencies]
reqwest = { version = "0.11.18", default-features = false, features = ["blocking"] }
tempfile = "3.8.0"
